
name: test
on: push
jobs:

  prisma_1:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          version: 12

      - name: 1 global + global on ${{ matrix.os }}
        if: always()  
        run: sh prisma/1.sh
  prisma_2:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          version: 12        
      - name: 2 global + local on ${{ matrix.os }}
        if: always()  
        run: sh prisma/2.sh
  prisma_3:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          version: 12
      - name: 3 global + npx with empty package.json on ${{ matrix.os }}
        if: always()  
        run: sh prisma/3.sh
  prisma_4:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          version: 12
      - name: 4 global + npx with already in package.json on ${{ matrix.os }}
        if: always() 
        run: sh prisma/4.sh
  prisma_5:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          version: 12
      - name: 5 local + global on ${{ matrix.os }}
        if: always() 
        run: sh prisma/5.sh
  prisma_6:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          version: 12
      - name: 6 local + local on ${{ matrix.os }}
        if: always() 
        run: sh prisma/6.sh
  prisma_7:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          version: 12
      - name: 7 local + npx with empty package.json on ${{ matrix.os }}
        if: always() 
        run: sh prisma/7.sh
  prisma_8:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          version: 12
      - name: 8 local + npx with already in package.json on ${{ matrix.os }}
        if: always() 
        run: sh prisma/8.sh

  prismaOld:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          version: 12

      - name: 1 global + global on ${{ matrix.os }}
        if: always()  
        run: sh prismaOld/1.sh
        
      - name: 2 global + local on ${{ matrix.os }}
        if: always()  
        run: sh prismaOld/2.sh
        
      - name: 3 global + npx with empty package.json on ${{ matrix.os }}
        if: always()  
        run: sh prismaOld/3.sh
        
      - name: 4 global + npx with already in package.json on ${{ matrix.os }}
        if: always() 
        run: sh prismaOld/4.sh
        
      - name: 5 local + global on ${{ matrix.os }}
        if: always() 
        run: sh prismaOld/5.sh
        
      - name: 6 local + local on ${{ matrix.os }}
        if: always() 
        run: sh prismaOld/6.sh

      - name: 7 local + npx with empty package.json on ${{ matrix.os }}
        if: always() 
        run: sh prismaOld/7.sh
        
      - name: 8 local + npx with already in package.json on ${{ matrix.os }}
        if: always() 
        run: sh prismaOld/8.sh

  prisma2:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          version: 12

      - name: 1 global + global on ${{ matrix.os }}
        if: always() 
        run: sh prisma2/1.sh
        
      - name: 2 global + local on ${{ matrix.os }}
        if: always() 
        run: sh prisma2/2.sh
        
      - name: 3 global + npx with empty package.json on ${{ matrix.os }}
        if: always() 
        run: sh prisma2/3.sh
        
      - name: 4 global + npx with already in package.json on ${{ matrix.os }}
        if: always() 
        run: sh prisma2/4.sh
        
      - name: 5 local + global on ${{ matrix.os }}
        if: always() 
        run: sh prisma2/5.sh
        
      - name: 6 local + local on ${{ matrix.os }}
        if: always() 
        run: sh prisma2/6.sh

      - name: 7 local + npx with empty package.json on ${{ matrix.os }}
        if: always() 
        run: sh prisma2/7.sh
        
      - name: 8 local + npx with already in package.json on ${{ matrix.os }}
        if: always() 
        run: sh prisma2/8.sh