
name: test
on: push
jobs:

  prisma:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          version: 12

      - name: 1 global + global on ${{ matrix.os }}
        if: always()  
        run: sh prisma/1.sh
        
      - name: 2 global + local on ${{ matrix.os }}
        if: always()  
        run: sh prisma/2.sh
        
      - name: 3 global + npx with empty package.json on ${{ matrix.os }}
        if: always()  
        run: sh prisma/3.sh
        
      - name: 4 global + npx with already in package.json on ${{ matrix.os }}
        if: always() 
        run: sh prisma/4.sh
        
      - name: test 5 on ${{ matrix.os }}
        if: always() 
        run: sh prisma/5.sh
        
      - name: test 6 on ${{ matrix.os }}
        if: always() 
        run: sh prisma/6.sh

      - name: test 7 on ${{ matrix.os }}
        if: always() 
        run: sh prisma/7.sh
        
      - name: test 8 on ${{ matrix.os }}
        if: always() 
        run: sh prisma/8.sh

  prisma2:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          version: 12

      - name: 1 global + global on ${{ matrix.os }}
        if: always() 
        run: sh prisma2/1.sh
        
      - name: 2 global + local on ${{ matrix.os }}
        if: always() 
        run: sh prisma2/2.sh
        
      - name: 3 global + npx with empty package.json on ${{ matrix.os }}
        if: always() 
        run: sh prisma2/3.sh
        
      - name: 4 global + npx with already in package.json on ${{ matrix.os }}
        if: always() 
        run: sh prisma2/4.sh
        
      - name: test 5 on ${{ matrix.os }}
        if: always() 
        run: sh prisma2/5.sh
        
      - name: test 6 on ${{ matrix.os }}
        if: always() 
        run: sh prisma2/6.sh

      - name: test 7 on ${{ matrix.os }}
        if: always() 
        run: sh prisma2/7.sh
        
      - name: test 8 on ${{ matrix.os }}
        if: always() 
        run: sh prisma2/8.sh