name: test
on: push
jobs:
  prisma:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        type: ['-g', '']
        combination:
          - '"prisma2@2.0.0-preview023" "@prisma/cli@2.0.0-alpha.993"'
          - '"prisma2@2.0.0-preview023" "@prisma/cli@2.0.0-alpha.1000"'
          - '"prisma" "@prisma/cli@2.0.0-alpha.1000"'

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          version: 12

      - name: ${{ matrix.combination }} on ${{ matrix.os }}
        if: always()
        run: sh run.sh ${{ matrix.combination }} "${{ matrix.b }}"
